### ISSUE TITLE
Search algorithm

### ISSUE THREAD

**Issue by vishalbollu** [jrmistry/teamform-seed#11]
Be able search with string input by:
- skill name
- team name
- member name

Toggle mode to search only for teams or members

**Comment by Yuuki-chan** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Search algorithm](https://trello.com/c/UcDylvKu/20-search-algorithm)

**Comment by Yuuki-chan** [comment]
afead92f81e62544e09bfca41bdab9228d336770
