### ISSUE TITLE
Embed Youtube video into team management platform

### ISSUE THREAD

**Issue by mallikatrivedi** [jrmistry/teamform-seed#13]
After the Youtube tutorial video has been completed we need to create the UI to embed this into our application. This includes beautifying it as well as organizing where to include this within the application.

**Comment by Yuuki-chan** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Embed Youtube video into team management platform](https://trello.com/c/3vypM43h/18-embed-youtube-video-into-team-management-platform)
