### ISSUE TITLE
Service for search

### ISSUE THREAD

**Issue by vishalbollu** [jrmistry/teamform-seed#14]
Search is used in several areas. Create a directive for search with some attributes so that it can be custom-used in different webpages.

**Comment by Yuuki-chan** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Directive for search](https://trello.com/c/1Jj42E7W/17-directive-for-search)

**Comment by Yuuki-chan** [comment]
afead92f81e62544e09bfca41bdab9228d336770
