### ISSUE TITLE
The user interface of the team's profile

### ISSUE THREAD

**Issue by jrmistry** [jrmistry/teamform-seed#15]
This represents the user interface (HTML/css) code of the team member's profile

**Comment by Yuuki-chan** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [The user interface of the team's profile](https://trello.com/c/dlAt98eh/16-the-user-interface-of-the-team-s-profile)

**Comment by Yuuki-chan** [comment]
212701139d536bbf0cd2be0fd63a344a165b82f2
