### ISSUE TITLE
Leave team functionality for team members

### ISSUE THREAD

**Issue by mallikatrivedi** [jrmistry/teamform-seed#19]
Before the deadline (set by the team leader), current team members have the option to leave the team. We need to add this functionality and its corresponding UI to the team member's page.

**Comment by Yuuki-chan** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Leave team functionality for team members](https://trello.com/c/75w2IN9U/12-leave-team-functionality-for-team-members)
