### ISSUE TITLE
Display team card

### ISSUE THREAD

**Issue by vishalbollu** [jrmistry/teamform-seed#21]
A UI representation of a team that will display some of the information that has been inputted on the team profile page. This UI will be used when displaying search results.

**Comment by Yuuki-chan** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Display team card](https://trello.com/c/IVv1Hu6g/10-display-team-card)

**Comment by Yuuki-chan** [comment]
No longer using this team card.
