### ISSUE TITLE
Leave event/Delete member functionality

### ISSUE THREAD

**Issue by mallikatrivedi** [jrmistry/teamform-seed#24]
A team member exists as long as he/she is part of a specific event. Every member can be a part of strictly one event. If they choose to leave the event, their profile is deleted and they must create a new profile in order to join a new event. 

We need to add this functionality to the team member's page as well as polish the UI for this.

**Comment by Yuuki-chan** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Leave event/Delete member functionality](https://trello.com/c/OljeUAW7/7-leave-event-delete-member-functionality)
