### ISSUE TITLE
Final UI overhaul and review

### ISSUE THREAD

**Issue by mallikatrivedi** [jrmistry/teamform-seed#26]
Since the tasks are divided up amongst our team members, it is possible to have difference in styles and color themes etc. We need to ensure that we keep a consistent UI throughout our application and follow a certain styling guideline.

**Comment by Yuuki-chan** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Final UI overhaul and review](https://trello.com/c/TiALfkOx/5-final-ui-overhaul-and-review)

**Comment by Yuuki-chan** [comment]
Done.
