### ISSUE TITLE
Setup Firebase

### ISSUE THREAD

**Issue by jrmistry** [jrmistry/teamform-seed#27]
Setup the Firebase database for this project. Migrate the code from the TA's firebase to our firebase. Make sure it is functional and populated.

**Comment by Yuuki-chan** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Setup Firebase](https://trello.com/c/qvi9VC71/4-setup-firebase)

**Comment by Yuuki-chan** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Invitation sending for team leaders](https://trello.com/c/8lhleuet/25-invitation-sending-for-team-leaders)

**Comment by Yuuki-chan** [comment]
fe195ce8f8196aeda8b3380bbe3ef31af2c12615 (actual commit)
37916f09849513be23be8c82d5619b97cf270f7b (merge)
