### ISSUE TITLE
Proto.io application prototype for the website

### ISSUE THREAD

**Issue by jrmistry** [jrmistry/teamform-seed#28]
Make a prototype for the new website user interface to show how the website will look like. This can be made on proto.io, otherwise make it on another platform which would be a better option.

**Comment by Yuuki-chan** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Proto.io application prototype for the website](https://trello.com/c/NpF8AU2q/3-proto-io-application-prototype-for-the-website)

**Comment by mallikatrivedi** [comment]
Decided against doing this since our team is working quite closely together.
