### ISSUE TITLE
Host the application on Amazon Web Services

### ISSUE THREAD

**Issue by jrmistry** [jrmistry/teamform-seed#29]
Host the application on my AWS student account. Make sure the code is fully functional.

**Comment by Yuuki-chan** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Host the application on Amazon Web Services](https://trello.com/c/7Si5dzQ5/2-host-the-application-on-amazon-web-services)

**Comment by Yuuki-chan** [comment]
Closing this as this is no longer necessary.
