### ISSUE TITLE
Deadline Functionality For Events

### ISSUE THREAD

**Issue by Doerrler** [jrmistry/teamform-seed#3]
Need to add the option for event deadlines, providing event creators with the choice to set an auto-fill date. If the deadline date is reached teamform will automatically assign all remaining members to teams.

**Comment by Yuuki-chan** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Deadline Functionality For Events](https://trello.com/c/kA52WbU4/28-deadline-functionality-for-events)
