### ISSUE TITLE
Team member can request to join a team 

### ISSUE THREAD

**Issue by mallikatrivedi** [jrmistry/teamform-seed#5]
As a team member I want to be able to request to join a team that interests me. 
How it works:
-Team member creates his/her profile
-Team member searches for a team or is recommended a team
-Team member requests to join a team (invitation sent to the team leader of requested team).

**Comment by Yuuki-chan** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Team member can request to join a team](https://trello.com/c/p9hDk9vH/26-team-member-can-request-to-join-a-team)
